In [1]:
import pandas as pd

In [2]:
file_path = '/kaggle/input/male-fertility/DIB dataset and codebook.xlsx'
df = pd.read_excel(file_path)

In [3]:
# Calculate the mean of OS1 to OS35 and assign it to the new column OS
df['JS'] = df.loc[:, 'JS1':'JS36'].sum(axis=1)

def min_max_normalize(column):
    min_val = column.min()
    max_val = column.max()
    normalized_column = (column - min_val) / (max_val - min_val)
    return normalized_column

df['JS_norm'] = min_max_normalize(df['JS'])

#Creating Labels of target column JS

rating = []
for row in df['JS_norm']:
    if row <= 0.5:
        rating.append(0)
    else:
        rating.append(1)
df['MMN_Label'] = rating

In [4]:
df.drop(columns=['JS1', 'JS2', 'JS3', 'JS4', 'JS5', 'JS6', 'JS7', 'JS8', 'JS9', 'JS10', 'JS11', 'JS12', 'JS13', 'JS14', 'JS15', 'JS16', 'JS17', 'JS18', 'JS19', 'JS20', 'JS21', 'JS22', 'JS23', 'JS24', 'JS25', 'JS26', 'JS27', 'JS28', 'JS29', 'JS30', 'JS31', 'JS32', 'JS33', 'JS34', 'JS35', 'JS36'], inplace=True)
df = df.drop(columns=['ID', 'JS_norm', 'JS'])
df = df.drop(columns=['JP1', 'JP2', 'JP3', 'JP4', 'JP5', 'JP6'])

In [5]:
income_mapping = {1: 'less than RM2,500', 2: 'RM2,500 - RM 3,169', 3: 'RM3,170 - RM3,969', 4: 'RM3,970 - RM4,849', 5: 'RM4,850 - RM5,879', 6: 'RM5,880 - RM7,099', 7: 'RM7,110 - RM8,699', 8: 'RM8,700 - RM10,959', 9: 'RM10,960 - RM15,039', 10: 'RM15,040 or more'}

columns_to_map = ['Household income']

# Map values in each column
for col in columns_to_map:
    df[col] = df[col].map(income_mapping)

In [6]:
os1_mapping = {1: 'never', 2: 'seldom', 3: 'sometimes', 4: 'often', 5: 'always'}

columns_to_map = ['OS1', 'OS2', 'OS3', 'OS4', 'OS5', 'OS6', 'OS7', 'OS8', 'OS9', 'OS10', 'OS11', 'OS12', 'OS13', 'OS14',
                  'OS15', 'OS16', 'OS17', 'OS18', 'OS19', 'OS20', 'OS21', 'OS22', 'OS23', 'OS24', 'OS25', 'OS26', 'OS27',
                  'OS28', 'OS29', 'OS30', 'OS31', 'OS32', 'OS33', 'OS34', 'OS35']

# Map values in each column
for col in columns_to_map:
    df[col] = df[col].map(os1_mapping)

In [7]:
os2_mapping = {1: 'yes, often', 2: 'yes, sometimes', 3: 'rarely', 4: 'no, never'}

columns_to_map = ['OS36']

# Map values in each column
for col in columns_to_map:
    df[col] = df[col].map(os2_mapping)

In [8]:
os3_mapping = {1: 'yes, certainly', 2: 'yes, to a certain degree', 3: 'yes, but only very little', 4: 'no, not at all'}

columns_to_map = ['OS37', 'OS38', 'OS39']

# Map values in each column
for col in columns_to_map:
    df[col] = df[col].map(os3_mapping)

In [9]:
cols_to_drop  = ['Age', 'Religion', 'Ethnicity', 'Marital status', 'Marriage period', 
                 'No. of children', 'Educational level', 'Employment status', 'Working period',
                 'Sperm quality', 'OS2', 'OS3', 'OS4', 'OS9', 'OS10', 'OS13','OS22', 'OS24', 
                 'OS25', 'OS26', 'OS28', 'OS34', 'OS36', 'OS39', 'OS40', 'OS41']

df.drop(columns=cols_to_drop, inplace=True)

In [18]:
column_names_mapping = {
    'Household income': 'What is your average household income?',
    'OS1': 'Different groups at work demand things from me that are hard to combine.',
    'OS5': 'I am unable to take sufficient breaks.',
    'OS6': 'I am pressured to work long hours.',
    'OS7': 'I have to work very fast.',
    'OS8': 'I have unrealistic time pressures.',
    'OS11': 'I have choice in deciding how I do my work.',
    'OS12': 'I have a choice in deciding what I do at work.',
    'OS14': 'My working time can be flexible.',
    'OS15': 'I am given supportive feedback on the work I do.',
    'OS16': 'I can rely on my line manager to help me out with a work problem.',
    'OS17': 'I can talk to my line manager about something that has upset or annoyed me about work.',
    'OS18': 'I am supported through emotionally demanding work.',
    'OS19': 'My line manager encourages me at work.',
    'OS20': 'If work gets difficult, my colleagues will help me.',
    'OS21': 'I get help and support I need from colleagues.',
    'OS23': 'My colleagues are willing to listen to my work-related problems.',
    'OS27': 'I am clear about the goals and objectives for my department.',
    'OS29': 'I have sufficient opportunities to question managers about change at work.',
    'OS30': 'Staff are always consulted about change at work.',
    'OS31': 'When changes are made at work, I am clear how they will work out in practice.',
    'OS32': 'I am subject to personal harassment in the form of unkind words or behaviour.',
    'OS33': 'There is friction or anger between colleagues.',
    'OS35': 'Relationships at work are strained.',
    'OS37': 'Do you feel that your work drains so much of your energy that it has a negative effect on your private life?',
    'OS38': 'Do you feel that your work takes so much of your time that it has a negative effect on your private life?',
}

df.rename(columns=column_names_mapping, inplace=True)

In [19]:
df.columns

Index(['What is your average household income?',
       'Different groups at work demand things from me that are hard to combine.',
       'I am unable to take sufficient breaks.',
       'I am pressured to work long hours.', 'I have to work very fast.',
       'I have unrealistic time pressures.',
       'I have choice in deciding how I do my work.',
       'I have a choice in deciding what I do at work.',
       'My working time can be flexible.',
       'I am given supportive feedback on the work I do.',
       'I can rely on my line manager to help me out with a work problem.',
       'I can talk to my line manager about something that has upset or annoyed me about work.',
       'I am supported through emotionally demanding work.',
       'My line manager encourages me at work.',
       'If work gets difficult, my colleagues will help me.',
       'I get help and support I need from colleagues.',
       'My colleagues are willing to listen to my work-related problems.',
       'I am clear about the goals and objectives for my department.',
       'I have sufficient opportunities to question managers about change at work.',
       'Staff are always consulted about change at work.',
       'When changes are made at work, I am clear how they will work out in practice.',
       'I am subject to personal harassment in the form of unkind words or behaviour.',
       'There is friction or anger between colleagues.',
       'Relationships at work are strained.',
       'Do you feel that your work drains so much of your energy that it has a negative effect on your private life?',
       'Do you feel that your work takes so much of your time that it has a negative effect on your private life?',
       'MMN_Label'],
      dtype='object')

In [22]:
def generate_text(row):
    return (
        f"The average household income of an individual is {row['What is your average household income?']}. "
        f"He {row['Different groups at work demand things from me that are hard to combine.']} feels that different groups at work demand things from him that are hard to combine, "
        f"and he is {row['I am unable to take sufficient breaks.']} unable to take sufficient breaks. "
        f"He {row['I am pressured to work long hours.']} feels that he is pressured to work long hours, "
        f"he {row['I have to work very fast.']} has to work very fast, "
        f"and he {row['I have unrealistic time pressures.']} has unrealistic time pressures. "
        f"Also, he {row['I have choice in deciding how I do my work.']} has choice in deciding how he does his work, "
        f"and he {row['I have a choice in deciding what I do at work.']} has a choice in deciding what he does at work. "
        f"His working time can {row['My working time can be flexible.']} be flexible, "
        f"he is {row['I am given supportive feedback on the work I do.']} given supportive feedback on the work he does, "
        f"he can {row['I can rely on my line manager to help me out with a work problem.']} rely on his line manager to help him out with a work problem, and "
        f"he can {row['I can talk to my line manager about something that has upset or annoyed me about work.']} talk to his line manager about something that has upset or annoyed him about work. "
        f"He is {row['I am supported through emotionally demanding work.']} supported through emotionally demanding work, "
        f"his line manager {row['My line manager encourages me at work.']} encourages him at work, "
        f"if work gets difficult, his colleagues will {row['If work gets difficult, my colleagues will help me.']} help him, "
        f"he {row['I get help and support I need from colleagues.']} gets help and support he needs from colleagues, and "
        f"he also responds his colleagues are {row['My colleagues are willing to listen to my work-related problems.']} willing to listen to his work-related problems. "
        f"He further responds he is {row['I am clear about the goals and objectives for my department.']} clear about the goals and objectives for his department, and "
        f"he {row['I have sufficient opportunities to question managers about change at work.']} has sufficient opportunities to question managers about change at work. "
        f"He responds as {row['Staff are always consulted about change at work.']} for the question asked, staff are always consulted about change at work. "
        f"When changes are made at work, he is {row['When changes are made at work, I am clear how they will work out in practice.']} clear about how they will work out in practice. "
        f"He is {row['I am subject to personal harassment in the form of unkind words or behaviour.']} subject to personal harassment in the form of unkind words or behaviour. "
        f"He feels there is {row['There is friction or anger between colleagues.']} friction or anger between colleagues, and "
        f"relationships at work are {row['Relationships at work are strained.']} strained. "
        f"He {row['Do you feel that your work drains so much of your energy that it has a negative effect on your private life?']} feels that his work drains so much of his energy that it has a negative effect on his private life. "
        f"He also feels that his work {row['Do you feel that your work takes so much of your time that it has a negative effect on your private life?']} takes so much of his time that it has a negative effect on his private life."
    )

df['Text'] = df.apply(generate_text, axis=1)

In [23]:
df2 = df[['Text', 'MMN_Label']]

df2.head()

                                                Text  MMN_Label
0  The average household income of an individual ...          1
1  The average household income of an individual ...          0
2  The average household income of an individual ...          1
3  The average household income of an individual ...          1
4  The average household income of an individual ...          1

In [24]:
# Save the resulting DataFrame to a CSV file
df2.to_csv('text_gen_mmn.csv', index=False)

In [25]:
import nltk
from nltk.tokenize import word_tokenize

In [26]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [27]:
df['Num_Tokens'] = df['Text'].apply(lambda x: len(word_tokenize(x)))

In [28]:
print(df[['Text', 'Num_Tokens']])

                                                  Text  Num_Tokens
0    The average household income of an individual ...         368
1    The average household income of an individual ...         370
2    The average household income of an individual ...         368
3    The average household income of an individual ...         368
4    The average household income of an individual ...         368
..                                                 ...         ...
304  The average household income of an individual ...         368
305  The average household income of an individual ...         370
306  The average household income of an individual ...         371
307  The average household income of an individual ...         365
308  The average household income of an individual ...         370

[309 rows x 2 columns]

In [29]:
df['Num_Tokens'].describe()

count    309.000000
mean     368.957929
std        1.284843
min      364.000000
25%      368.000000
50%      369.000000
75%      370.000000
max      371.000000
Name: Num_Tokens, dtype: float64